In [4]:
import pandas as pd

In [9]:
#df = pd.read_csv(r'C:\dysk\CV — kopia\Naukaa\Python\Data\csv_files\layoffs.csv')
#df
df = pd.read_table(r'C:\dysk\CV — kopia\Naukaa\Python\Data\csv_files\layoffs.csv', sep=',')
df

,company,location,industry,total_laid_off,percentage_laid_off,date,stage,country,funds_raised_millions
0,Atlassian,Sydney,Other,500.0,0.05,3/6/2023,Post-IPO,Australia,210.0
1,SiriusXM,New York City,Media,475.0,0.08,3/6/2023,Post-IPO,United States,525.0
2,Alerzo,Ibadan,Retail,400.0,NaN,3/6/2023,Series B,Nigeria,16.0
3,UpGrad,Mumbai,Education,120.0,NaN,3/6/2023,Unknown,India,631.0
4,Loft,Sao Paulo,Real Estate,340.0,0.15,3/3/2023,Unknown,Brazil,788.0
...,...,...,...,...,...,...,...,...,...
2356,Blackbaud,Charleston,Other,500.0,0.14,NaN,Post-IPO,United States,NaN
2357,Yahoo,SF Bay Area,Consumer,1600.0,0.20,2/9/2023,Acquired,United States,6.0
2358,Hibob,Tel Aviv,HR,70.0,0.30,3/30/2020,Series A,Israel,45.0
2359,Casper,New York City,Retail,NaN,NaN,9/14/2021,Post-IPO,United States,339.0
2360,Wildlife Studios,Sao Paulo,Consumer,300.0,0.20,11/28/2022,Unknown,Brazil,260.0

Jesli chcemt konkretny sheet w excel

In [16]:
df2 = pd.read_excel(r'C:\dysk\CV — kopia\Naukaa\PowerBI\data\01_Apocolypse Food Prep.xlsx', sheet_name='Sheet1')
df2

      Store            Product  Price       Date
0   Walmart               Rice  25.00 2022-01-01
1    Costco               Rice  23.00 2022-01-01
2    Target               Rice  22.99 2022-01-01
3   Walmart               Rice  25.75 2022-02-01
4    Costco               Rice  23.99 2022-02-01
5    Target               Rice  23.25 2022-02-01
6   Walmart               Rice  26.99 2022-03-01
7    Costco               Rice  24.99 2022-03-01
8    Target               Rice  24.25 2022-03-01
9   Walmart               Rice  26.99 2022-04-01
10   Costco               Rice  25.25 2022-04-01
11   Target               Rice  24.75 2022-04-01
12  Walmart        Dried Beans  22.99 2022-01-01
13   Costco        Dried Beans  20.99 2022-01-01
14   Target        Dried Beans  23.99 2022-01-01
15  Walmart        Dried Beans  23.99 2022-02-01
16   Costco        Dried Beans  22.99 2022-02-01
17   Target        Dried Beans  24.99 2022-02-01
18  Walmart        Dried Beans  24.25 2022-03-01
19   Costco        Dried Beans  22.99 2022-03-01
20   Target        Dried Beans  25.45 2022-03-01
21  Walmart        Dried Beans  24.49 2022-04-01
22   Costco        Dried Beans  23.99 2022-04-01
23   Target        Dried Beans  25.79 2022-04-01
24  Walmart     Bottled Water    5.00 2022-01-01
25   Costco     Bottled Water    4.25 2022-01-01
26   Target     Bottled Water    4.99 2022-01-01
27  Walmart     Bottled Water    5.25 2022-02-01
28   Costco     Bottled Water    4.49 2022-02-01
29   Target     Bottled Water    5.15 2022-02-01
30  Walmart     Bottled Water    5.45 2022-03-01
31   Costco     Bottled Water    4.80 2022-03-01
32   Target     Bottled Water    5.25 2022-03-01
33  Walmart     Bottled Water    5.75 2022-04-01
34   Costco     Bottled Water    4.89 2022-04-01
35   Target     Bottled Water    5.35 2022-04-01
36  Walmart  Canned Vegetables   0.65 2022-01-01
37   Costco  Canned Vegetables   0.85 2022-01-01
38   Target  Canned Vegetables   0.65 2022-01-01
39  Walmart  Canned Vegetables   0.75 2022-02-01
40   Costco  Canned Vegetables   0.85 2022-02-01
41   Target  Canned Vegetables   0.69 2022-02-01
42  Walmart  Canned Vegetables   0.85 2022-03-01
43   Costco  Canned Vegetables   0.85 2022-03-01
44   Target  Canned Vegetables   0.74 2022-03-01
45  Walmart  Canned Vegetables   1.00 2022-04-01
46   Costco  Canned Vegetables   0.85 2022-04-01
47   Target  Canned Vegetables   0.79 2022-04-01
48  Walmart               Milk   2.00 2022-01-01
49   Costco               Milk   2.30 2022-01-01
50   Target               Milk   2.20 2022-01-01
51  Walmart               Milk   2.10 2022-02-01
52   Costco               Milk   2.40 2022-02-01
53   Target               Milk   2.45 2022-02-01
54  Walmart               Milk   2.40 2022-03-01
55   Costco               Milk   2.50 2022-03-01
56   Target               Milk   2.70 2022-03-01
57  Walmart               Milk   2.90 2022-04-01
58   Costco               Milk   2.70 2022-04-01
59   Target               Milk   3.00 2022-04-01

In [17]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Store    60 non-null     str
 1   Product  60 non-null     str
 2   Price    60 non-null     float64
 3   Date     60 non-null     datetime64[us]
dtypes: datetime64[us](1), float64(1), str(2)
memory usage: 2.0 KB